FROM maven:3.9-eclipse-temurin-17
WORKDIR /app
COPY pom.xml .
# Go offline to cache dependencies
RUN mvn dependency:go-offline
COPY src ./src
# Run with devtools and remote debugging enabled
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]
